#!/bin/bash
path=$PWD
sed -i "/ExecStart=/c\ExecStart\=$path/venv/bin/python $path/kiln-controller.py" lib/init/kiln-controller.service
sudo cp $path/lib/init/kiln-controller.service /etc/systemd/system/
sudo systemctl enable kiln-controller
